/* Generated By:JavaCC: Do not edit this line. CommentStripParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommentStripParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OTHER = 1;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<OTHER>",
    "<token of kind 2>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 5>",
  };

}
